### ISSUE TITLE
Добавить в список имеет класс planned

### ISSUE THREAD

**Issue by regs01** [shikimori/shikimori#2812]
Добавить в список имеет класс `.b-add_to_list.planned`, как и Запланировано. Так что разделить цветами то, что запланировано и ещё не запланировано (не изучено) не получается.

Лучше бы недобавленным либо не иметь дополнительного класса `.b-add_to_list`, либо что-нибудь типа `.b-add_to_list.unlisted`.

**Comment by grin3671** [comment]
> Так что разделить цветами то, что запланировано и ещё не запланировано (не изучено) не получается.

В CSS можно использовать не только классы:
```css
/* Добавить в список */
.b-add_to_list [data-method="POST"] .trigger,
.b-add_to_list [data-method="POST"] .option {
  background: #e8ebef;
  border-color: #d8dde4;
  color: #123;
}
```
А вообще для таких вопросов есть [CSS-клуб](https://shikimori.one/clubs/811).
